apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dronerunner-scale
  namespace: drone
spec:
  scaleTargetRef:
    kind: Deployment
    name: dronerunner
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 60
  pollingInterval: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.metrics.svc.cluster.local
        metricName: drone_builds
        query: |
          drone_pending_builds + drone_running_builds + drone_pending_jobs + drone_running_jobs
        threshold: "1"